# Copyright 2021 Canonical
# See LICENSE file for licensing details.

options:

  ### Application-related options:
  #
  # TODO(aznashwan): add a separate option for https endpoints?
  # Will need to see what certificates needs installing and where.

  server-ui-path:
    type: string
    default: /studio
    description: |
      The root path (exluding protocol, host, or port declaration) under
      which the Studio UI should be server.

  server-logging-level:
    type: string
    default: INFO
    description: |
      String identifier of the log level to be used for all library classes.
      Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  server-pac4j-logging-level:
    type: string
    default: DEBUG
    description: |
      String identifier of the log level to be used by authentication-related
      PAC4J actions. Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  # TODO(aznashwan): remove these after gitlab relation defined:
  gitlab-client-id:
    type: string
  gitlab-client-secret:
    type: string
